Save image after test

diff --git a/.github/workflows/polaris-build.yml b/.github/workflows/polaris-build.yml
--- a/.github/workflows/polaris-build.yml
+++ b/.github/workflows/polaris-build.yml
@@ -22,7 +22,7 @@ jobs:
       - name: Save built-production-image
         uses: actions/upload-artifact@v2.2.4
         with:
-          name: built-production-image
+          name: built-image
           path: /opt/pharo/Pharo.image
           if-no-files-found: error
           retention-days: 1
@@ -47,17 +47,26 @@ jobs:
           path: /opt/pharo/
 
       - name: Run Tests of Polaris
-        run: pharo /opt/pharo/Pharo.image test --fail-on-failure --fail-on-error Polaris-Tests;
+        run: pharo /opt/pharo/Pharo.image test --fail-on-failure --fail-on-error Polaris-Tests --save;
 
       - name: Save built-production-image
         uses: actions/upload-artifact@v2.2.4
         if: success() || failure()
         with:
-          name: Save Pharo Logs
-          path: |
-              /opt/pharo/
-              !/opt/pharo/pharo-local
-               #/opt/pharo/std*
-               #/opt/pharo/*.log
-          if-no-files-found: warn
+          name: test-image-saved
+          path: /opt/pharo/Pharo.image
+          if-no-files-found: error
           retention-days: 1
+
+#      - name: Save built-production-image
+#        uses: actions/upload-artifact@v2.2.4
+#        if: success() || failure()
+#        with:
+#          name: Save Pharo Logs
+#          path: |
+#              /opt/pharo/
+#              !/opt/pharo/pharo-local
+#               #/opt/pharo/std*
+#               #/opt/pharo/*.log
+#          if-no-files-found: warn
+#          retention-days: 1
